FROM node:16-alpine
LABEL maintainer = "Tomer Groisman"

RUN mkdir /app
WORKDIR /app
COPY ./build /app

RUN npm install -g npm@latest
RUN npm install -g serve

EXPOSE 3000

CMD serve -l 3000 -s build
