language: python
python: 
  - "3.9"

services:
  - docker

before_script: pip install docker-compose

script: 
  - docker-compose run client sh -c "npm run test-no-watch"
  - docker-compose run server sh -c "python manage.py wait_for_db && python manage.py && flake8"