version: "3.3"

services: 
  nginx:
    container_name: tower-of-hanoi-nginx
    depends_on:
      - client
      - server
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"

  client:
    container_name: tower-of-hanoi-client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes: 
      - ./client:/app
      - /app/node_modules

  server:
    container_name: tower-of-hanoi-server
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes: 
      - ./server/src:/app
    environment:
      - HOST_NAME=server
      - DJANGO_SUPERUSER_EMAIL=test@gmail.com
      - DJANGO_SUPERUSER_PASSWORD=123456
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASSWORD=supersecretpassword
    depends_on:
      - db

  db:
    container_name: tower-of-hanoi-db
    image: postgres:13.3-alpine
    environment: 
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword 