version: "3"

services: 
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes: 
      - ./client:/app
      - /app/node_modules
    container_name: towe-of-hanoi-client
    stdin_open: true
    command: >
      sh -c "npm start"