version: "3.7"

services: 

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      - server

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - ./env/client.env

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./env/server.env
    volumes:
      - static_volume:/app/staticfiles

volumes:
  static_volume: