version: "3.7"

services: 

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      - server

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_ENDPOINT=$REACT_APP_API_ENDPOINT
    ports:
      - "8081:8081"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./env/server.env
    volumes:
      - static_volume:/app/staticfiles

volumes:
  static_volume: