version: "3"

services: 
  nginx:
    container_name: tower-of-hanoi-nginx
    image: tomergroisman/toh-nginx
    ports:
      - "80:80"
    depends_on:
      - client
      - server

  client:
    container_name: tower-of-hanoi-client
    image: tomergroisman/toh-client
    env_file:
      - ./env/client.env

  server:
    container_name: tower-of-hanoi-server
    image: tomergroisman/toh-server
    env_file:
      - ./env/server.env