version: "3"

services: 
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes: 
      - ./client:/app
      - /app/node_modules
    container_name: towe-of-hanoi-client
    stdin_open: true
    command: >
      sh -c "npm start"

  server:
    build:
      context: ./server
    ports:
      - "3232:3232"
    volumes: 
      - ./server/src:/app
    container_name: towe-of-hanoi-server
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:3232"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASSWORD=supersecretpassword
    depends_on:
      - db

  db:
    image: postgres:13.3-alpine
    container_name: towe-of-hanoi-db
    environment: 
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword 