version: "3.4.3"

services: 
  nginx:
    container_name: tower-of-hanoi-nginx
    image: tomergroisman/tower-of-hanoi-nginx
    depends_on:
      - client
      - server
    restart: always
    ports:
      - "80:80"

  client:
    container_name: tower-of-hanoi-client
    image: tomergroisman/tower-of-hanoi-client
    env_file:
      - ./env/client.env  
    restart: on-failure

  server:
    container_name: tower-of-hanoi-server
    image: tomergroisman/tower-of-hanoi-server
    env_file:
      - ./env/server.env    
    restart: on-failure
    depends_on:
      - db

  db:
    container_name: tower-of-hanoi-db
    image: postgres:13.3-alpine
    env_file:
      - ./env/db.env