# Generated by Django 3.2.5 on 2021-07-09 13:38

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=core.fields.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=core.fields.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
