# Generated by Django 3.2.5 on 2021-07-10 11:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='level',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='record',
            name='moves',
            field=models.PositiveIntegerField(),
        ),
    ]
