# Generated by Django 3.2.5 on 2021-07-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210710_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='record',
            name='moves',
            field=models.IntegerField(),
        ),
    ]
