# Generated by Django 3.2.5 on 2021-07-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210710_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='is_best',
            field=models.BooleanField(default=False),
        ),
    ]
