# Generated by Django 3.2.5 on 2021-07-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_record_is_best'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='nickname',
            field=models.CharField(default='tomer', max_length=255),
            preserve_default=False,
        ),
    ]
