# Generated by Django 3.2.5 on 2021-07-10 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_record_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='nickname',
        ),
    ]
