# Generated by Django 3.2.5 on 2021-07-10 17:42

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_record_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'required': 'Email address is required', 'unique': 'User with this email address already exists'}, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=core.fields.CharField(blank=True, error_messages={'unique': 'User with this nickname already exists'}, max_length=255, null=True, unique=True),
        ),
    ]
