# Generated by Django 3.2.5 on 2021-07-18 18:13

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210710_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='icon',
            field=core.fields.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'blank': 'Email address is required', 'required': 'Email address is required', 'unique': 'User with this email address already exists'}, max_length=255, unique=True),
        ),
    ]
